#!/usr/bin/env python3
"""One-time importer for the historical integrated Zhanyue HTML.

The generated files become the maintained source. Normal builds never read the
historical HTML; rerun this importer only when intentionally rebasing from a
different integrated artifact.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


STYLE_RE = re.compile(r"<style(?P<attrs>[^>]*)>(?P<body>.*?)</style>", re.DOTALL)
SCRIPT_RE = re.compile(r"<script(?P<attrs>[^>]*)>(?P<body>.*?)</script>", re.DOTALL)
ID_RE = re.compile(r'\bid=["\']([^"\']+)["\']')


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def _split_base_script(script: str) -> dict[str, str]:
    data_end = re.search(r"\blet\s+LINES\s*=\s*DATA\.lines\s*;", script)
    if not data_end:
        raise SystemExit("Cannot locate `let LINES = DATA.lines;` in base script")
    body = script[data_end.end() :].lstrip()

    anchors = [
        ("core.js", "const SVG_NS", "function renderRoutes"),
        ("rendering.js", "function renderRoutes", "const reducedMotionQuery"),
        ("viewport.js", "const reducedMotionQuery", "const SPELLING_SCHEME_LABELS"),
        ("practice.js", "const SPELLING_SCHEME_LABELS", "function pushUndo"),
        ("review-audio.js", "function pushUndo", "function renderTransferHubs"),
        (
            "render-orchestration.js",
            "function renderTransferHubs",
            'document.querySelectorAll(".mode-btn").forEach(btn=>btn.addEventListener',
        ),
        (
            "bootstrap.js",
            'document.querySelectorAll(".mode-btn").forEach(btn=>btn.addEventListener',
            None,
        ),
    ]
    output: dict[str, str] = {}
    for name, start_marker, end_marker in anchors:
        start = body.find(start_marker)
        if start < 0:
            raise SystemExit(f"Cannot locate base-script marker: {start_marker}")
        end = len(body) if end_marker is None else body.find(end_marker, start + 1)
        if end < 0:
            raise SystemExit(f"Cannot locate base-script marker: {end_marker}")
        output[name] = body[start:end]
    return output


def import_html(source: Path, destination: Path) -> None:
    html = source.read_text(encoding="utf-8")

    style_names: list[str] = []
    for index, match in enumerate(STYLE_RE.finditer(html), start=1):
        style_id = (ID_RE.search(match.group("attrs")) or [None, f"style-{index:02d}"])[1]
        name = f"{index:02d}-{style_id}.css"
        style_names.append(name)
        _write(destination / "review" / "styles" / name, match.group("body"))

    scripts = list(SCRIPT_RE.finditer(html))
    if not scripts:
        raise SystemExit("No scripts found in integrated HTML")

    base_parts = _split_base_script(scripts[0].group("body"))
    for name, content in base_parts.items():
        _write(destination / "review" / "runtime" / name, content)

    feature_names: list[str] = []
    unnamed_feature_names = ["camera-follow-v34"]
    unnamed_index = 0
    for index, match in enumerate(scripts[1:], start=1):
        script_id_match = ID_RE.search(match.group("attrs"))
        if script_id_match:
            feature_id = script_id_match.group(1)
        else:
            feature_id = unnamed_feature_names[unnamed_index] if unnamed_index < len(unnamed_feature_names) else f"feature-{index:02d}"
            unnamed_index += 1
        name = f"{index:02d}-{feature_id}.js"
        feature_names.append(name)
        _write(destination / "review" / "features" / name, match.group("body"))

    template = STYLE_RE.sub("", html)
    template = SCRIPT_RE.sub("", template)
    template = template.replace("</head>", "  <!-- ZHANYUE_STYLES -->\n</head>", 1)
    template = template.replace("</body>", "  <!-- ZHANYUE_SCRIPTS -->\n</body>", 1)
    _write(destination / "review" / "index.template.html", template)

    manifest = [
        "# Generated by tools/import_integrated.py; build.py consumes this order.",
        "[styles]",
        *style_names,
        "",
        "[runtime]",
        *base_parts.keys(),
        "",
        "[features]",
        *feature_names,
    ]
    _write(destination / "review" / "source-order.txt", "\n".join(manifest))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    import_html(args.source.resolve(), args.destination.resolve())


if __name__ == "__main__":
    main()
