export const LEARN_PRODUCTS = Object.freeze({
  bus: Object.freeze({
    id: 'bus',
    title: '站粤公交',
    documentTitle: '站粤公交 · 深圳公交拼音与粤语学习',
    subtitle: 'Shenzhen Bus Typing',
    mark: '巴',
    vehicle: 'bus',
    introPill: '固定全网相对位置 · 单线轨道式重排',
    introTitle: '沿着一条公交线路，<br>记住深圳的每一个站。',
    introText: '搜索线路或直接点击线网，进入公交站名拼音与粤语练习。',
    loadingTitle: '正在读取公交线网',
    loadingText: '全网总览使用 Canvas，选中线路后再加载详细站点。',
    mapLabel: '深圳公交线路学习地图',
    focusMapLabel: '当前公交线路示意图',
    realMapLabel: '当前公交线路真实地图',
    feedback: '先输入起点站名，公交车会保持原位。',
    movingNoun: '公交车',
    networkLinkLabel: '公交图',
    collectorUrl: '/bus/collector',
    networkUrl: '/bus',
    learnUrl: '/bus/learn',
  }),
  metro: Object.freeze({
    id: 'metro',
    title: '站粤地铁',
    documentTitle: '站粤地铁 · 深圳地铁拼音与粤语学习',
    subtitle: 'Shenzhen Metro Typing',
    mark: '轨',
    vehicle: 'metro',
    introPill: '人工复核示意 · 沉浸线路练习',
    introTitle: '沿着深圳地铁，<br>记住每一个站。',
    introText: '选择一条地铁线路，进入人工复核示意图、拼音与粤语练习。',
    loadingTitle: '正在读取地铁线网',
    loadingText: '全网总览使用 Canvas，选中线路后加载人工复核示意和完整站序。',
    mapLabel: '深圳地铁线路学习地图',
    focusMapLabel: '当前地铁线路示意图',
    realMapLabel: '当前地铁线路真实地图',
    feedback: '先输入起点站名，列车会保持原位。',
    movingNoun: '列车',
    networkLinkLabel: '地铁图',
    collectorUrl: '/metro/collector',
    networkUrl: '/metro',
    learnUrl: '/metro/learn',
  }),
});

export function learnProduct(network) {
  return LEARN_PRODUCTS[network] || LEARN_PRODUCTS.bus;
}
